--- #YAML:1.0
name:               Number-Range
version:            0.11
abstract:           Perl extension defining ranges of numbers and testing if a
author:
    - Larry Shatzer, Jr. <larrysh@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
